
// Optimized Ranker Weights - Generated by PrecisionOptimizer
// Configuration: Feature-Driven Optimization
// Expected gain: +20-25%

const OPTIMIZED_WEIGHTS: Required<RankerWeights> = {
  alpha: 0.7,
  beta: 0.4,
  w1: 0.3, // telehealth match boost
  w2: 0.15, // telehealth mismatch penalty  
  w3: 0.25, // after-hours match boost
  w4: 0.2, // duration threshold boost
  w5: 0.1, // duration short penalty
  w6: 0.15, // chronic category boost
};

// To apply: Replace DEFAULT_WEIGHTS with OPTIMIZED_WEIGHTS in ranker.service.ts
